# Generated by Django 6.1 on 2026-09-28 18:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_category_currency'),
        ('tenants', '0002_tenant_usd_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('debt_balance_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('debt_balance_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('last_notified_debt_step_uzs', models.IntegerField(default=0)),
                ('last_notified_debt_step_usd', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_counterparty_in_shops', to='tenants.tenant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'counterparties',
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('is_correction', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.counterparty')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_debt_payments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('b2b_transfer_request', "B2B O'tkazma so'rovi"), ('b2b_transfer_accepted', 'B2B Qabul qilindi'), ('b2b_transfer_partially_accepted', 'B2B Qisman qabul qilindi'), ('b2b_transfer_rejected', 'B2B Rad etildi'), ('b2b_transfer_cancelled', 'B2B Bekor qilindi'), ('debt_threshold_warning', 'Qarz chegarasi ogohlantirishi')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=32)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3)),
                ('is_partner_sale', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('debt', 'Nasiya')], default='cash', max_length=10)),
                ('status', models.CharField(choices=[('completed', 'Tugallangan'), ('partially_voided', 'Qisman bekor qilingan'), ('voided', 'Bekor qilingan'), ('b2b_pending', 'B2B Kutilmoqda'), ('b2b_partially_accepted', 'B2B Qisman qabul qilingan'), ('b2b_accepted', 'B2B Qabul qilingan'), ('b2b_rejected', 'B2B Rad etilgan')], default='completed', max_length=32)),
                ('b2b_expires_at', models.DateTimeField(blank=True, null=True)),
                ('b2b_reject_reason', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('b2b_target_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_b2b_sales', to='tenants.tenant')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.counterparty')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_partner_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('partially_voided', 'Qisman bekor qilingan'), ('voided', 'Bekor qilingan'), ('b2b_accepted', 'B2B Qabul qilingan'), ('b2b_rejected', 'B2B Rad etilgan')], default='active', max_length=32)),
                ('voided_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('b2b_accepted_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('b2b_rejected_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.productvariant')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SaleVoidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.TextField()),
                ('voided_at', models.DateTimeField(auto_now_add=True)),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='void_logs', to='sales.saleitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('voided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_void_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voided_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone_number'), name='unique_counterparty_phone_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('tenant', 'receipt_number'), name='unique_sale_receipt_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_item_quantity_positive'),
        ),
    ]
