# Generated by Django 6.1 on 2026-09-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_seed_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('b2b_transfer_request', "B2B O'tkazma so'rovi"), ('b2b_transfer_accepted', 'B2B Qabul qilindi'), ('b2b_transfer_partially_accepted', 'B2B Qisman qabul qilindi'), ('b2b_transfer_rejected', 'B2B Rad etildi'), ('b2b_transfer_cancelled', 'B2B Bekor qilindi'), ('debt_threshold_warning', 'Qarz chegarasi ogohlantirishi'), ('daily_z_report', 'Kunlik Z-Hisobot')], max_length=32),
        ),
    ]
