# Generated by Django 6.1 on 2026-09-29 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_tenant_daily_report_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('price_change', 'Price Change'), ('employee_hire', 'Employee Hire'), ('employee_fire', 'Employee Fire'), ('owner_transfer', 'Owner Transfer'), ('void_sale', 'Void Sale'), ('stock_adjustment', 'Stock Adjustment'), ('cash_discrepancy', 'Cash Discrepancy'), ('login_attempt', 'Login Attempt'), ('password_reset', 'Password Reset')], db_index=True, max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'action', '-created_at'], name='core_auditl_tenant__76b1e5_idx')],
            },
        ),
    ]
