# Generated by Django 6.1 on 2026-09-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_permissions'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('kirim', 'Kirim'), ('sotuv', 'Sotuv'), ('mijoz_qaytardi', 'Mijoz qaytardi'), ('yetkazib_beruvchiga_qaytarish', 'Yetkazib beruvchiga qaytarish'), ('isrofgarchilik', 'Isrofgarchilik'), ('tuzatish', 'Tuzatish')], max_length=32),
        ),
    ]
