# Generated by Django 6.1 on 2026-10-08 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage'),
        ('inventory', '0003_stockmovement_sale_alter_stockmovement_type'),
        ('tenants', '0007_populate_default_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('reject_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='stock',
            name='custom_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Filial uchun maxsus minimal narx', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='custom_price_partner',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Filial uchun maxsus hamkor narxi', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='custom_price_recommended',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Filial uchun maxsus tavsiya etilgan sotuv narxi', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='tenants.branch'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.productvariant'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('kirim', 'Kirim'), ('sotuv', 'Sotuv'), ('mijoz_qaytardi', 'Mijoz qaytardi'), ('yetkazib_beruvchiga_qaytarish', 'Yetkazib beruvchiga qaytarish'), ('isrofgarchilik', 'Isrofgarchilik'), ('tuzatish', 'Tuzatish'), ('transfer_out', "Filialga o'tkazish (chiqim)"), ('transfer_in', 'Filialdan qabul qilish (kirim)')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('branch', 'product_variant'), name='unique_stock_per_branch_variant'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.stocktransfer'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transfer_item_quantity_positive'),
        ),
    ]
