"""Management command to seed ~100 realistic retail products into a tenant's main branch.
Supports idempotent runs: if a product already exists, skips or updates stock.
"""

from decimal import Decimal
from django.core.management.base import BaseCommand
from django.db import transaction

from apps.tenants.models import Tenant
from apps.accounts.models import User
from apps.catalog.models import Category, Product, ProductVariant
from apps.catalog.services import ProductService
from apps.inventory.services import StockService


CATEGORIES_DATA = [
    {
        "name": "Ichimliklar va sharbatlar",
        "kod": "30",
        "currency": "UZS",
    },
    {
        "name": "Oziq-ovqat va baqqollik",
        "kod": "31",
        "currency": "UZS",
    },
    {
        "name": "Choy, qahva va nonushta",
        "kod": "32",
        "currency": "UZS",
    },
    {
        "name": "Sut va sut mahsulotlari",
        "kod": "33",
        "currency": "UZS",
    },
    {
        "name": "Shirinliklar va pishiriqlar",
        "kod": "34",
        "currency": "UZS",
    },
    {
        "name": "Maishiy kimyo va tozalash",
        "kod": "35",
        "currency": "UZS",
    },
    {
        "name": "Shaxsiy gigiyena",
        "kod": "36",
        "currency": "UZS",
    },
    {
        "name": "Elektronika va aksessuarlar",
        "kod": "37",
        "currency": "UZS",
    },
]

PRODUCTS_DATA = [
    # --- 1. Ichimliklar va sharbatlar (20 ta) ---
    {
        "name": "Coca-Cola Classic 1.5L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("11000"),
        "price_partner": Decimal("13000"),
        "price_min": Decimal("13500"),
        "price_recommended": Decimal("15000"),
        "quantity": Decimal("60"),
        "barcode": "478000200001",
    },
    {
        "name": "Coca-Cola Classic 0.5L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("5500"),
        "price_partner": Decimal("6500"),
        "price_min": Decimal("7000"),
        "price_recommended": Decimal("8000"),
        "quantity": Decimal("80"),
        "barcode": "478000200002",
    },
    {
        "name": "Coca-Cola Classic 1L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("8500"),
        "price_partner": Decimal("10000"),
        "price_min": Decimal("10500"),
        "price_recommended": Decimal("12000"),
        "quantity": Decimal("50"),
        "barcode": "478000200003",
    },
    {
        "name": "Fanta Orange 1.5L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("11000"),
        "price_partner": Decimal("13000"),
        "price_min": Decimal("13500"),
        "price_recommended": Decimal("15000"),
        "quantity": Decimal("40"),
        "barcode": "478000200004",
    },
    {
        "name": "Fanta Orange 0.5L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("5500"),
        "price_partner": Decimal("6500"),
        "price_min": Decimal("7000"),
        "price_recommended": Decimal("8000"),
        "quantity": Decimal("50"),
        "barcode": "478000200005",
    },
    {
        "name": "Sprite 1.5L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("11000"),
        "price_partner": Decimal("13000"),
        "price_min": Decimal("13500"),
        "price_recommended": Decimal("15000"),
        "quantity": Decimal("40"),
        "barcode": "478000200006",
    },
    {
        "name": "Sprite 0.5L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("5500"),
        "price_partner": Decimal("6500"),
        "price_min": Decimal("7000"),
        "price_recommended": Decimal("8000"),
        "quantity": Decimal("50"),
        "barcode": "478000200007",
    },
    {
        "name": "Pepsi Cola 1.5L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("10500"),
        "price_partner": Decimal("12500"),
        "price_min": Decimal("13000"),
        "price_recommended": Decimal("14500"),
        "quantity": Decimal("55"),
        "barcode": "478000200008",
    },
    {
        "name": "Pepsi Cola 0.5L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("5000"),
        "price_partner": Decimal("6000"),
        "price_min": Decimal("6500"),
        "price_recommended": Decimal("7500"),
        "quantity": Decimal("70"),
        "barcode": "478000200009",
    },
    {
        "name": "Dinay Olma sharbati 1L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("9000"),
        "price_partner": Decimal("11000"),
        "price_min": Decimal("11500"),
        "price_recommended": Decimal("13000"),
        "quantity": Decimal("45"),
        "barcode": "478000200010",
    },
    {
        "name": "Dinay Shaftoli sharbati 1L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("9000"),
        "price_partner": Decimal("11000"),
        "price_min": Decimal("11500"),
        "price_recommended": Decimal("13000"),
        "quantity": Decimal("40"),
        "barcode": "478000200011",
    },
    {
        "name": "Dinay Olcha sharbati 1L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("9000"),
        "price_partner": Decimal("11000"),
        "price_min": Decimal("11500"),
        "price_recommended": Decimal("13000"),
        "quantity": Decimal("35"),
        "barcode": "478000200012",
    },
    {
        "name": "Bliss Anor sharbati 1L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("12000"),
        "price_partner": Decimal("14000"),
        "price_min": Decimal("14500"),
        "price_recommended": Decimal("16500"),
        "quantity": Decimal("30"),
        "barcode": "478000200013",
    },
    {
        "name": "Bliss Apelsin sharbati 1L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("12000"),
        "price_partner": Decimal("14000"),
        "price_min": Decimal("14500"),
        "price_recommended": Decimal("16500"),
        "quantity": Decimal("30"),
        "barcode": "478000200014",
    },
    {
        "name": "Nestle Pure Life gazsiz suv 1.5L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("3500"),
        "price_partner": Decimal("4500"),
        "price_min": Decimal("4800"),
        "price_recommended": Decimal("5500"),
        "quantity": Decimal("100"),
        "barcode": "478000200015",
    },
    {
        "name": "Nestle Pure Life gazsiz suv 0.5L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("2000"),
        "price_partner": Decimal("2800"),
        "price_min": Decimal("3000"),
        "price_recommended": Decimal("3500"),
        "quantity": Decimal("120"),
        "barcode": "478000200016",
    },
    {
        "name": "Chortoq gazli mineral suv 0.5L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("4500"),
        "price_partner": Decimal("5500"),
        "price_min": Decimal("6000"),
        "price_recommended": Decimal("7000"),
        "quantity": Decimal("60"),
        "barcode": "478000200017",
    },
    {
        "name": "Hydrolife toza suv 1.5L",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("3200"),
        "price_partner": Decimal("4000"),
        "price_min": Decimal("4200"),
        "price_recommended": Decimal("5000"),
        "quantity": Decimal("80"),
        "barcode": "478000200018",
    },
    {
        "name": "Flash Up energetik ichimlik 450ml",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("6500"),
        "price_partner": Decimal("8000"),
        "price_min": Decimal("8500"),
        "price_recommended": Decimal("9500"),
        "quantity": Decimal("50"),
        "barcode": "478000200019",
    },
    {
        "name": "Red Bull energetik ichimlik 250ml",
        "category_kod": "30",
        "unit": "dona",
        "cost_price": Decimal("18000"),
        "price_partner": Decimal("21000"),
        "price_min": Decimal("22000"),
        "price_recommended": Decimal("25000"),
        "quantity": Decimal("40"),
        "barcode": "478000200020",
    },

    # --- 2. Oziq-ovqat va baqqollik (20 ta) ---
    {
        "name": "Makfa oliy navli bug'doy uni 2kg",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("22000"),
        "price_partner": Decimal("25000"),
        "price_min": Decimal("26000"),
        "price_recommended": Decimal("29000"),
        "quantity": Decimal("40"),
        "barcode": "478000200021",
    },
    {
        "name": "Makfa oliy navli bug'doy uni 1kg",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("11500"),
        "price_partner": Decimal("13000"),
        "price_min": Decimal("13500"),
        "price_recommended": Decimal("15000"),
        "quantity": Decimal("50"),
        "barcode": "478000200022",
    },
    {
        "name": "Makfa spagetti makaron 450g",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("8500"),
        "price_partner": Decimal("10000"),
        "price_min": Decimal("10500"),
        "price_recommended": Decimal("12000"),
        "quantity": Decimal("60"),
        "barcode": "478000200023",
    },
    {
        "name": "Makfa spiral makaron 450g",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("8500"),
        "price_partner": Decimal("10000"),
        "price_min": Decimal("10500"),
        "price_recommended": Decimal("12000"),
        "quantity": Decimal("60"),
        "barcode": "478000200024",
    },
    {
        "name": "Shedevr tozalangan kungaboqar yog'i 1L",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("16500"),
        "price_partner": Decimal("18500"),
        "price_min": Decimal("19000"),
        "price_recommended": Decimal("21000"),
        "quantity": Decimal("70"),
        "barcode": "478000200025",
    },
    {
        "name": "Shedevr tozalangan kungaboqar yog'i 5L",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("78000"),
        "price_partner": Decimal("86000"),
        "price_min": Decimal("88000"),
        "price_recommended": Decimal("96000"),
        "quantity": Decimal("25"),
        "barcode": "478000200026",
    },
    {
        "name": "Oila tanlovi paxta yog'i 1L",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("15000"),
        "price_partner": Decimal("17000"),
        "price_min": Decimal("17500"),
        "price_recommended": Decimal("19500"),
        "quantity": Decimal("40"),
        "barcode": "478000200027",
    },
    {
        "name": "Lazzat Alanga guruchi 1kg",
        "category_kod": "31",
        "unit": "kg",
        "cost_price": Decimal("17000"),
        "price_partner": Decimal("19000"),
        "price_min": Decimal("20000"),
        "price_recommended": Decimal("22000"),
        "quantity": Decimal("80"),
        "barcode": "478000200028",
    },
    {
        "name": "Lazzat Lazer elita guruchi 1kg",
        "category_kod": "31",
        "unit": "kg",
        "cost_price": Decimal("24000"),
        "price_partner": Decimal("27000"),
        "price_min": Decimal("28000"),
        "price_recommended": Decimal("32000"),
        "quantity": Decimal("60"),
        "barcode": "478000200029",
    },
    {
        "name": "Xorazm oq tozalangan shakar 1kg",
        "category_kod": "31",
        "unit": "kg",
        "cost_price": Decimal("12000"),
        "price_partner": Decimal("13500"),
        "price_min": Decimal("14000"),
        "price_recommended": Decimal("15500"),
        "quantity": Decimal("100"),
        "barcode": "478000200030",
    },
    {
        "name": "Osh tuzi yodlangan Oshxona 1kg",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("2000"),
        "price_partner": Decimal("2600"),
        "price_min": Decimal("2800"),
        "price_recommended": Decimal("3500"),
        "quantity": Decimal("90"),
        "barcode": "478000200031",
    },
    {
        "name": "Rollton tovuqli tezpishar lapsha 60g",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("2800"),
        "price_partner": Decimal("3500"),
        "price_min": Decimal("3700"),
        "price_recommended": Decimal("4500"),
        "quantity": Decimal("120"),
        "barcode": "478000200032",
    },
    {
        "name": "Doshirak mol go'shtli lapsha 90g",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("6500"),
        "price_partner": Decimal("8000"),
        "price_min": Decimal("8500"),
        "price_recommended": Decimal("9500"),
        "quantity": Decimal("60"),
        "barcode": "478000200033",
    },
    {
        "name": "Baraka tabiiy tomat pastasi 800g",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("18000"),
        "price_partner": Decimal("21000"),
        "price_min": Decimal("22000"),
        "price_recommended": Decimal("25000"),
        "quantity": Decimal("40"),
        "barcode": "478000200034",
    },
    {
        "name": "Heinz klassik pomidorli ketchup 350g",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("14000"),
        "price_partner": Decimal("16500"),
        "price_min": Decimal("17000"),
        "price_recommended": Decimal("19500"),
        "quantity": Decimal("45"),
        "barcode": "478000200035",
    },
    {
        "name": "Calve zaytunli mayonez 400g",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("13000"),
        "price_partner": Decimal("15000"),
        "price_min": Decimal("15500"),
        "price_recommended": Decimal("18000"),
        "quantity": Decimal("50"),
        "barcode": "478000200036",
    },
    {
        "name": "Bonduelle yashil no'xat 400g",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("15000"),
        "price_partner": Decimal("17500"),
        "price_min": Decimal("18000"),
        "price_recommended": Decimal("21000"),
        "quantity": Decimal("35"),
        "barcode": "478000200037",
    },
    {
        "name": "Bonduelle shirin makkajo'xori 400g",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("16000"),
        "price_partner": Decimal("18500"),
        "price_min": Decimal("19000"),
        "price_recommended": Decimal("22000"),
        "quantity": Decimal("35"),
        "barcode": "478000200038",
    },
    {
        "name": "Greenfield Golden Ceylon choyi 100 paket",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("38000"),
        "price_partner": Decimal("43000"),
        "price_min": Decimal("44000"),
        "price_recommended": Decimal("48000"),
        "quantity": Decimal("30"),
        "barcode": "478000200039",
    },
    {
        "name": "Ahmad Tea Earl Grey qora choy 100g",
        "category_kod": "31",
        "unit": "dona",
        "cost_price": Decimal("21000"),
        "price_partner": Decimal("24500"),
        "price_min": Decimal("25000"),
        "price_recommended": Decimal("28000"),
        "quantity": Decimal("35"),
        "barcode": "478000200040",
    },

    # --- 3. Choy, qahva va nonushta (10 ta) ---
    {
        "name": "Tess Pleasure mevali choy 100g",
        "category_kod": "32",
        "unit": "dona",
        "cost_price": Decimal("19000"),
        "price_partner": Decimal("22000"),
        "price_min": Decimal("23000"),
        "price_recommended": Decimal("26000"),
        "quantity": Decimal("30"),
        "barcode": "478000200041",
    },
    {
        "name": "Nescafe Classic qahvasi 100g",
        "category_kod": "32",
        "unit": "dona",
        "cost_price": Decimal("28000"),
        "price_partner": Decimal("32000"),
        "price_min": Decimal("33000"),
        "price_recommended": Decimal("36000"),
        "quantity": Decimal("40"),
        "barcode": "478000200042",
    },
    {
        "name": "Jacobs Monarch eriydigan qahva 95g",
        "category_kod": "32",
        "unit": "dona",
        "cost_price": Decimal("39000"),
        "price_partner": Decimal("44000"),
        "price_min": Decimal("45000"),
        "price_recommended": Decimal("49000"),
        "quantity": Decimal("30"),
        "barcode": "478000200043",
    },
    {
        "name": "MacCoffee Original 3in1 paketcha 20g",
        "category_kod": "32",
        "unit": "dona",
        "cost_price": Decimal("1500"),
        "price_partner": Decimal("2000"),
        "price_min": Decimal("2200"),
        "price_recommended": Decimal("2500"),
        "quantity": Decimal("150"),
        "barcode": "478000200044",
    },
    {
        "name": "Nesquik shokoladli kakao 250g",
        "category_kod": "32",
        "unit": "dona",
        "cost_price": Decimal("26000"),
        "price_partner": Decimal("30000"),
        "price_min": Decimal("31000"),
        "price_recommended": Decimal("34000"),
        "quantity": Decimal("25"),
        "barcode": "478000200045",
    },
    {
        "name": "Uvelka jo'xori yormasi 400g",
        "category_kod": "32",
        "unit": "dona",
        "cost_price": Decimal("14000"),
        "price_partner": Decimal("16500"),
        "price_min": Decimal("17000"),
        "price_recommended": Decimal("19000"),
        "quantity": Decimal("30"),
        "barcode": "478000200046",
    },
    {
        "name": "Nutella shokoladli pasta 350g",
        "category_kod": "32",
        "unit": "dona",
        "cost_price": Decimal("48000"),
        "price_partner": Decimal("54000"),
        "price_min": Decimal("55000"),
        "price_recommended": Decimal("60000"),
        "quantity": Decimal("20"),
        "barcode": "478000200047",
    },
    {
        "name": "Quyultirilgan sut Alekseevskoe 380g",
        "category_kod": "32",
        "unit": "dona",
        "cost_price": Decimal("17000"),
        "price_partner": Decimal("20000"),
        "price_min": Decimal("20500"),
        "price_recommended": Decimal("23000"),
        "quantity": Decimal("40"),
        "barcode": "478000200048",
    },
    {
        "name": "Tog' asali tabiiy toza 500g",
        "category_kod": "32",
        "unit": "dona",
        "cost_price": Decimal("35000"),
        "price_partner": Decimal("41000"),
        "price_min": Decimal("42000"),
        "price_recommended": Decimal("47000"),
        "quantity": Decimal("25"),
        "barcode": "478000200049",
    },
    {
        "name": "Pista mag'izli halva 300g",
        "category_kod": "32",
        "unit": "dona",
        "cost_price": Decimal("13000"),
        "price_partner": Decimal("15500"),
        "price_min": Decimal("16000"),
        "price_recommended": Decimal("18500"),
        "quantity": Decimal("35"),
        "barcode": "478000200050",
    },

    # --- 4. Sut va sut mahsulotlari (10 ta) ---
    {
        "name": "Musaffo tabiiy sut 3.2% 1L",
        "category_kod": "33",
        "unit": "dona",
        "cost_price": Decimal("11500"),
        "price_partner": Decimal("13000"),
        "price_min": Decimal("13500"),
        "price_recommended": Decimal("15000"),
        "quantity": Decimal("50"),
        "barcode": "478000200051",
    },
    {
        "name": "Musaffo tabiiy sut 2.5% 1L",
        "category_kod": "33",
        "unit": "dona",
        "cost_price": Decimal("10500"),
        "price_partner": Decimal("12000"),
        "price_min": Decimal("12500"),
        "price_recommended": Decimal("14000"),
        "quantity": Decimal("50"),
        "barcode": "478000200052",
    },
    {
        "name": "Kamilka yangi qaymoq 200g",
        "category_kod": "33",
        "unit": "dona",
        "cost_price": Decimal("12000"),
        "price_partner": Decimal("14000"),
        "price_min": Decimal("14500"),
        "price_recommended": Decimal("16500"),
        "quantity": Decimal("40"),
        "barcode": "478000200053",
    },
    {
        "name": "President sariyog'i 82% 200g",
        "category_kod": "33",
        "unit": "dona",
        "cost_price": Decimal("29000"),
        "price_partner": Decimal("33000"),
        "price_min": Decimal("34000"),
        "price_recommended": Decimal("38000"),
        "quantity": Decimal("30"),
        "barcode": "478000200054",
    },
    {
        "name": "BioSut nordon qatiq 1L",
        "category_kod": "33",
        "unit": "dona",
        "cost_price": Decimal("9000"),
        "price_partner": Decimal("10500"),
        "price_min": Decimal("11000"),
        "price_recommended": Decimal("12500"),
        "quantity": Decimal("35"),
        "barcode": "478000200055",
    },
    {
        "name": "Danone qulupnayli yogurt 290g",
        "category_kod": "33",
        "unit": "dona",
        "cost_price": Decimal("9500"),
        "price_partner": Decimal("11000"),
        "price_min": Decimal("11500"),
        "price_recommended": Decimal("13000"),
        "quantity": Decimal("45"),
        "barcode": "478000200056",
    },
    {
        "name": "Rastishka tvorogi 100g",
        "category_kod": "33",
        "unit": "dona",
        "cost_price": Decimal("6500"),
        "price_partner": Decimal("7800"),
        "price_min": Decimal("8000"),
        "price_recommended": Decimal("9000"),
        "quantity": Decimal("40"),
        "barcode": "478000200057",
    },
    {
        "name": "Hochland erigan pishloq 140g",
        "category_kod": "33",
        "unit": "dona",
        "cost_price": Decimal("16000"),
        "price_partner": Decimal("18500"),
        "price_min": Decimal("19000"),
        "price_recommended": Decimal("21500"),
        "quantity": Decimal("35"),
        "barcode": "478000200058",
    },
    {
        "name": "Rossiyskiy qattiq pishloq 1kg",
        "category_kod": "33",
        "unit": "kg",
        "cost_price": Decimal("85000"),
        "price_partner": Decimal("96000"),
        "price_min": Decimal("98000"),
        "price_recommended": Decimal("110000"),
        "quantity": Decimal("20"),
        "barcode": "478000200059",
    },
    {
        "name": "Prostokvashino smetana 20% 300g",
        "category_kod": "33",
        "unit": "dona",
        "cost_price": Decimal("15000"),
        "price_partner": Decimal("17500"),
        "price_min": Decimal("18000"),
        "price_recommended": Decimal("20500"),
        "quantity": Decimal("40"),
        "barcode": "478000200060",
    },

    # --- 5. Shirinliklar va pishiriqlar (15 ta) ---
    {
        "name": "Snickers shokolad batonchigi 50g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("6000"),
        "price_partner": Decimal("7200"),
        "price_min": Decimal("7500"),
        "price_recommended": Decimal("8500"),
        "quantity": Decimal("80"),
        "barcode": "478000200061",
    },
    {
        "name": "Snickers Super shokolad 80g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("9500"),
        "price_partner": Decimal("11000"),
        "price_min": Decimal("11500"),
        "price_recommended": Decimal("13000"),
        "quantity": Decimal("60"),
        "barcode": "478000200062",
    },
    {
        "name": "Twix shokolad batonchigi 55g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("6000"),
        "price_partner": Decimal("7200"),
        "price_min": Decimal("7500"),
        "price_recommended": Decimal("8500"),
        "quantity": Decimal("70"),
        "barcode": "478000200063",
    },
    {
        "name": "Bounty kokosli shokolad 57g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("6000"),
        "price_partner": Decimal("7200"),
        "price_min": Decimal("7500"),
        "price_recommended": Decimal("8500"),
        "quantity": Decimal("70"),
        "barcode": "478000200064",
    },
    {
        "name": "Mars shokolad batonchigi 50g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("6000"),
        "price_partner": Decimal("7200"),
        "price_min": Decimal("7500"),
        "price_recommended": Decimal("8500"),
        "quantity": Decimal("60"),
        "barcode": "478000200065",
    },
    {
        "name": "KitKat shokoladli vafli 41.5g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("5500"),
        "price_partner": Decimal("6800"),
        "price_min": Decimal("7000"),
        "price_recommended": Decimal("8000"),
        "quantity": Decimal("65"),
        "barcode": "478000200066",
    },
    {
        "name": "Alpen Gold sutli shokolad 85g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("11000"),
        "price_partner": Decimal("13000"),
        "price_min": Decimal("13500"),
        "price_recommended": Decimal("15000"),
        "quantity": Decimal("50"),
        "barcode": "478000200067",
    },
    {
        "name": "Alpen Gold mayizli shokolad 85g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("11000"),
        "price_partner": Decimal("13000"),
        "price_min": Decimal("13500"),
        "price_recommended": Decimal("15000"),
        "quantity": Decimal("50"),
        "barcode": "478000200068",
    },
    {
        "name": "Milka sutli shokolad 100g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("16000"),
        "price_partner": Decimal("18500"),
        "price_min": Decimal("19000"),
        "price_recommended": Decimal("21500"),
        "quantity": Decimal("40"),
        "barcode": "478000200069",
    },
    {
        "name": "Orion Choco Pie pechenye 12 dona",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("24000"),
        "price_partner": Decimal("27500"),
        "price_min": Decimal("28000"),
        "price_recommended": Decimal("31000"),
        "quantity": Decimal("35"),
        "barcode": "478000200070",
    },
    {
        "name": "Oreo vanilli pechenye 95g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("7500"),
        "price_partner": Decimal("9000"),
        "price_min": Decimal("9500"),
        "price_recommended": Decimal("11000"),
        "quantity": Decimal("60"),
        "barcode": "478000200071",
    },
    {
        "name": "Barni ayiqcha biskviti 30g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("4000"),
        "price_partner": Decimal("5000"),
        "price_min": Decimal("5200"),
        "price_recommended": Decimal("6000"),
        "quantity": Decimal("75"),
        "barcode": "478000200072",
    },
    {
        "name": "Raffaello bodomli konfet 150g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("36000"),
        "price_partner": Decimal("41000"),
        "price_min": Decimal("42000"),
        "price_recommended": Decimal("47000"),
        "quantity": Decimal("25"),
        "barcode": "478000200073",
    },
    {
        "name": "Ferrero Rocher konfet to'plami 200g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("58000"),
        "price_partner": Decimal("66000"),
        "price_min": Decimal("68000"),
        "price_recommended": Decimal("76000"),
        "quantity": Decimal("20"),
        "barcode": "478000200074",
    },
    {
        "name": "Crafers shokoladli vafli 200g",
        "category_kod": "34",
        "unit": "dona",
        "cost_price": Decimal("9000"),
        "price_partner": Decimal("10800"),
        "price_min": Decimal("11000"),
        "price_recommended": Decimal("12500"),
        "quantity": Decimal("45"),
        "barcode": "478000200075",
    },

    # --- 6. Maishiy kimyo va tozalash (12 ta) ---
    {
        "name": "Ariel Oxi kir yuvish kukuni 3kg",
        "category_kod": "35",
        "unit": "dona",
        "cost_price": Decimal("68000"),
        "price_partner": Decimal("77000"),
        "price_min": Decimal("79000"),
        "price_recommended": Decimal("88000"),
        "quantity": Decimal("25"),
        "barcode": "478000200076",
    },
    {
        "name": "Ariel Color kir yuvish kukuni 1.5kg",
        "category_kod": "35",
        "unit": "dona",
        "cost_price": Decimal("36000"),
        "price_partner": Decimal("41000"),
        "price_min": Decimal("42000"),
        "price_recommended": Decimal("47000"),
        "quantity": Decimal("30"),
        "barcode": "478000200077",
    },
    {
        "name": "Tide Color kir yuvish kukuni 3kg",
        "category_kod": "35",
        "unit": "dona",
        "cost_price": Decimal("62000"),
        "price_partner": Decimal("70000"),
        "price_min": Decimal("72000"),
        "price_recommended": Decimal("80000"),
        "quantity": Decimal("25"),
        "barcode": "478000200078",
    },
    {
        "name": "Fairy limonli idish yuvish geli 450ml",
        "category_kod": "35",
        "unit": "dona",
        "cost_price": Decimal("14500"),
        "price_partner": Decimal("17000"),
        "price_min": Decimal("17500"),
        "price_recommended": Decimal("19500"),
        "quantity": Decimal("50"),
        "barcode": "478000200079",
    },
    {
        "name": "Fairy olma idish yuvish geli 900ml",
        "category_kod": "35",
        "unit": "dona",
        "cost_price": Decimal("26000"),
        "price_partner": Decimal("30000"),
        "price_min": Decimal("31000"),
        "price_recommended": Decimal("34500"),
        "quantity": Decimal("35"),
        "barcode": "478000200080",
    },
    {
        "name": "Domestos tozalovchi gel 750ml",
        "category_kod": "35",
        "unit": "dona",
        "cost_price": Decimal("19000"),
        "price_partner": Decimal("22000"),
        "price_min": Decimal("22500"),
        "price_recommended": Decimal("25500"),
        "quantity": Decimal("40"),
        "barcode": "478000200081",
    },
    {
        "name": "Mr. Proper pol yuvish vositasi 1L",
        "category_kod": "35",
        "unit": "dona",
        "cost_price": Decimal("23000"),
        "price_partner": Decimal("26500"),
        "price_min": Decimal("27000"),
        "price_recommended": Decimal("30500"),
        "quantity": Decimal("30"),
        "barcode": "478000200082",
    },
    {
        "name": "Lenor gullar ifori konditsioneri 1L",
        "category_kod": "35",
        "unit": "dona",
        "cost_price": Decimal("27000"),
        "price_partner": Decimal("31000"),
        "price_min": Decimal("32000"),
        "price_recommended": Decimal("36000"),
        "quantity": Decimal("25"),
        "barcode": "478000200083",
    },
    {
        "name": "Bref tualet tozalovchi blok 3 dona",
        "category_kod": "35",
        "unit": "dona",
        "cost_price": Decimal("22000"),
        "price_partner": Decimal("25000"),
        "price_min": Decimal("25500"),
        "price_recommended": Decimal("28500"),
        "quantity": Decimal("30"),
        "barcode": "478000200084",
    },
    {
        "name": "Cif universal tozalovchi krem 500ml",
        "category_kod": "35",
        "unit": "dona",
        "cost_price": Decimal("18000"),
        "price_partner": Decimal("21000"),
        "price_min": Decimal("21500"),
        "price_recommended": Decimal("24000"),
        "quantity": Decimal("30"),
        "barcode": "478000200085",
    },
    {
        "name": "Somat idish yuvish tabletkasi 20 dona",
        "category_kod": "35",
        "unit": "dona",
        "cost_price": Decimal("42000"),
        "price_partner": Decimal("48000"),
        "price_min": Decimal("49000"),
        "price_recommended": Decimal("55000"),
        "quantity": Decimal("20"),
        "barcode": "478000200086",
    },
    {
        "name": "Selpak oshxona sochiqlari 2 dona",
        "category_kod": "35",
        "unit": "dona",
        "cost_price": Decimal("14000"),
        "price_partner": Decimal("16500"),
        "price_min": Decimal("17000"),
        "price_recommended": Decimal("19500"),
        "quantity": Decimal("40"),
        "barcode": "478000200087",
    },

    # --- 7. Shaxsiy gigiyena (8 ta) ---
    {
        "name": "Colgate Total tish pastasi 100ml",
        "category_kod": "36",
        "unit": "dona",
        "cost_price": Decimal("19000"),
        "price_partner": Decimal("22500"),
        "price_min": Decimal("23000"),
        "price_recommended": Decimal("26000"),
        "quantity": Decimal("40"),
        "barcode": "478000200088",
    },
    {
        "name": "Colgate Triple Action tish pastasi 100ml",
        "category_kod": "36",
        "unit": "dona",
        "cost_price": Decimal("13000"),
        "price_partner": Decimal("15500"),
        "price_min": Decimal("16000"),
        "price_recommended": Decimal("18000"),
        "quantity": Decimal("50"),
        "barcode": "478000200089",
    },
    {
        "name": "Head & Shoulders mentol shampun 400ml",
        "category_kod": "36",
        "unit": "dona",
        "cost_price": Decimal("38000"),
        "price_partner": Decimal("43500"),
        "price_min": Decimal("44000"),
        "price_recommended": Decimal("49000"),
        "quantity": Decimal("30"),
        "barcode": "478000200090",
    },
    {
        "name": "Pantene Pro-V mayin shampun 400ml",
        "category_kod": "36",
        "unit": "dona",
        "cost_price": Decimal("36000"),
        "price_partner": Decimal("41000"),
        "price_min": Decimal("42000"),
        "price_recommended": Decimal("47000"),
        "quantity": Decimal("30"),
        "barcode": "478000200091",
    },
    {
        "name": "Dove ipakdek nozik krem-sovun 100g",
        "category_kod": "36",
        "unit": "dona",
        "cost_price": Decimal("11000"),
        "price_partner": Decimal("13000"),
        "price_min": Decimal("13500"),
        "price_recommended": Decimal("15000"),
        "quantity": Decimal("50"),
        "barcode": "478000200092",
    },
    {
        "name": "Duru qattiq sovun 4x90g",
        "category_kod": "36",
        "unit": "dona",
        "cost_price": Decimal("16000"),
        "price_partner": Decimal("18500"),
        "price_min": Decimal("19000"),
        "price_recommended": Decimal("21500"),
        "quantity": Decimal("40"),
        "barcode": "478000200093",
    },
    {
        "name": "Selpak yumshoq tualet qog'ozi 8 dona",
        "category_kod": "36",
        "unit": "dona",
        "cost_price": Decimal("28000"),
        "price_partner": Decimal("32500"),
        "price_min": Decimal("33000"),
        "price_recommended": Decimal("37000"),
        "quantity": Decimal("35"),
        "barcode": "478000200094",
    },
    {
        "name": "Familia nam salfetkalar 72 dona",
        "category_kod": "36",
        "unit": "dona",
        "cost_price": Decimal("8500"),
        "price_partner": Decimal("10200"),
        "price_min": Decimal("10500"),
        "price_recommended": Decimal("12000"),
        "quantity": Decimal("60"),
        "barcode": "478000200095",
    },

    # --- 8. Elektronika va aksessuarlar (10 ta) ---
    {
        "name": "Kingston DataTraveler 32GB fleshka",
        "category_kod": "37",
        "unit": "dona",
        "cost_price": Decimal("42000"),
        "price_partner": Decimal("48000"),
        "price_min": Decimal("50000"),
        "price_recommended": Decimal("58000"),
        "quantity": Decimal("25"),
        "barcode": "478000200096",
    },
    {
        "name": "Kingston DataTraveler 64GB fleshka",
        "category_kod": "37",
        "unit": "dona",
        "cost_price": Decimal("55000"),
        "price_partner": Decimal("63000"),
        "price_min": Decimal("65000"),
        "price_recommended": Decimal("75000"),
        "quantity": Decimal("25"),
        "barcode": "478000200097",
    },
    {
        "name": "Borofone Type-C tezkor kabel 1m",
        "category_kod": "37",
        "unit": "dona",
        "cost_price": Decimal("15000"),
        "price_partner": Decimal("18500"),
        "price_min": Decimal("20000"),
        "price_recommended": Decimal("25000"),
        "quantity": Decimal("40"),
        "barcode": "478000200098",
    },
    {
        "name": "Borofone Lightning kabel 1m",
        "category_kod": "37",
        "unit": "dona",
        "cost_price": Decimal("15000"),
        "price_partner": Decimal("18500"),
        "price_min": Decimal("20000"),
        "price_recommended": Decimal("25000"),
        "quantity": Decimal("40"),
        "barcode": "478000200099",
    },
    {
        "name": "Hoco 18W tezkor zaryadlash adapteri",
        "category_kod": "37",
        "unit": "dona",
        "cost_price": Decimal("35000"),
        "price_partner": Decimal("42000"),
        "price_min": Decimal("45000"),
        "price_recommended": Decimal("55000"),
        "quantity": Decimal("30"),
        "barcode": "478000200100",
    },
    {
        "name": "Hoco 10000mAh Powerbank",
        "category_kod": "37",
        "unit": "dona",
        "cost_price": Decimal("110000"),
        "price_partner": Decimal("125000"),
        "price_min": Decimal("130000"),
        "price_recommended": Decimal("150000"),
        "quantity": Decimal("20"),
        "barcode": "478000200101",
    },
    {
        "name": "Remax simsiz quloqchin (TWS)",
        "category_kod": "37",
        "unit": "dona",
        "cost_price": Decimal("130000"),
        "price_partner": Decimal("150000"),
        "price_min": Decimal("155000"),
        "price_recommended": Decimal("180000"),
        "quantity": Decimal("15"),
        "barcode": "478000200102",
    },
    {
        "name": "A4Tech OP-620D USB optik sichqoncha",
        "category_kod": "37",
        "unit": "dona",
        "cost_price": Decimal("45000"),
        "price_partner": Decimal("52000"),
        "price_min": Decimal("55000"),
        "price_recommended": Decimal("65000"),
        "quantity": Decimal("25"),
        "barcode": "478000200103",
    },
    {
        "name": "Duracell Basic AA batareya 2 dona",
        "category_kod": "37",
        "unit": "dona",
        "cost_price": Decimal("14000"),
        "price_partner": Decimal("16500"),
        "price_min": Decimal("17000"),
        "price_recommended": Decimal("20000"),
        "quantity": Decimal("50"),
        "barcode": "478000200104",
    },
    {
        "name": "Duracell Basic AAA batareya 2 dona",
        "category_kod": "37",
        "unit": "dona",
        "cost_price": Decimal("14000"),
        "price_partner": Decimal("16500"),
        "price_min": Decimal("17000"),
        "price_recommended": Decimal("20000"),
        "quantity": Decimal("50"),
        "barcode": "478000200105",
    },
]


class Command(BaseCommand):
    help = "Seed ~100 realistic retail products with positive stock into the main branch"

    def add_arguments(self, parser):
        parser.add_argument(
            "--tenant-id",
            type=int,
            default=4,
            help="Tenant ID to seed products into (default: 4)",
        )

    def handle(self, *args, **options):
        tenant_id = options["tenant_id"]
        try:
            tenant = Tenant.objects.get(id=tenant_id)
        except Tenant.DoesNotExist:
            self.stderr.write(self.style.ERROR(f"Tenant with ID {tenant_id} not found."))
            return

        main_branch = tenant.get_main_branch()
        if not main_branch:
            self.stderr.write(self.style.ERROR(f"Tenant {tenant.name} has no main branch."))
            return

        owner = User.objects.filter(tenant=tenant, role="owner").first()
        if not owner:
            owner = User.objects.filter(tenant=tenant).first()

        self.stdout.write(
            self.style.NOTICE(
                f"--- Seeding for Tenant: '{tenant.name}' (ID: {tenant.id}) | Branch: '{main_branch.name}' (ID: {main_branch.id}) ---"
            )
        )

        # 1. Ensure Categories exist
        categories = {}
        for cat_data in CATEGORIES_DATA:
            category, created = Category.objects.get_or_create(
                tenant=tenant,
                kod=cat_data["kod"],
                defaults={
                    "name": cat_data["name"],
                    "currency": cat_data["currency"],
                },
            )
            if not created and category.name != cat_data["name"]:
                category.name = cat_data["name"]
                category.save(update_fields=["name"])
            categories[cat_data["kod"]] = category

        self.stdout.write(self.style.SUCCESS(f"Loaded {len(categories)} categories."))

        # 2. Seed Products
        created_count = 0
        skipped_count = 0
        intake_count = 0
        total_units = Decimal("0")
        total_cost = Decimal("0")

        for item in PRODUCTS_DATA:
            category = categories.get(item["category_kod"])
            if not category:
                self.stderr.write(self.style.WARNING(f"Category {item['category_kod']} not found for {item['name']}"))
                continue

            # Check if product already exists
            product = Product.objects.filter(tenant=tenant, name=item["name"]).first()
            if not product:
                with transaction.atomic():
                    product = ProductService.create(
                        tenant=tenant,
                        name=item["name"],
                        category=category,
                        price_partner=item["price_partner"],
                        price_min=item["price_min"],
                        price_recommended=item["price_recommended"],
                        unit=item["unit"],
                        barcode=item.get("barcode"),
                    )
                    created_count += 1
            else:
                skipped_count += 1
                # If variant doesn't have barcode, update it
                variant = product.variants.first()
                if variant and not variant.barcode and item.get("barcode"):
                    variant.barcode = item["barcode"]
                    variant.save(update_fields=["barcode"])

            variant = product.variants.first()
            if not variant:
                continue

            # Check stock in main_branch
            stock = variant.stocks.filter(branch=main_branch).first()
            if not stock or stock.quantity <= 0:
                StockService.intake(
                    tenant=tenant,
                    branch=main_branch,
                    product_variant=variant,
                    quantity=item["quantity"],
                    cost_price=item["cost_price"],
                    created_by=owner,
                    note="Boshlang'ich qoldiq (Avtomatik to'ldirish)",
                )
                intake_count += 1
                total_units += item["quantity"]
                total_cost += (item["quantity"] * item["cost_price"])
            else:
                total_units += stock.quantity
                total_cost += (stock.quantity * (stock.last_cost_price or item["cost_price"]))

        self.stdout.write(
            self.style.SUCCESS(
                f"\nFinished seeding products:\n"
                f"- Yangi yaratilgan mahsulotlar: {created_count}\n"
                f"- Mavjud bo'lgan mahsulotlar: {skipped_count}\n"
                f"- Kirim qilingan partiyalar: {intake_count}\n"
                f"- Jami ombordagi qoldiq (dona/kg): {total_units}\n"
                f"- Jami tan narxi qiymati: {total_cost:,.2f} UZS\n"
                f"- Filial: '{main_branch.name}'\n"
            )
        )
