# Generated by Django 6.1 on 2026-10-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_terms_accepted_user_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Doimiy aloqa raqami'),
        ),
    ]
