# Generated by Django 6.1 on 2026-10-08 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_contact_phone'),
        ('tenants', '0007_populate_default_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Xodim biriktirilgan filial (agar ko'rsatilsa, xodim faqat shu filialda ishlaydi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='tenants.branch'),
        ),
    ]
