# Generated by Django 6.1 on 2026-09-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='usd_rate',
            field=models.DecimalField(decimal_places=2, default=12800.0, help_text="Ichki dollar kursi (ko'rgazmali hisoblash uchun)", max_digits=12),
        ),
    ]
