# Generated by Django 6.1 on 2026-09-29 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_usd_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='daily_report_time',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Kunlik Z-hisobot xabari yuboriladigan vaqt (masalan 22:00)'),
        ),
    ]
