# Generated by Django 6.1 on 2026-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_daily_report_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='daily_report_target',
            field=models.CharField(choices=[('personal', 'Faqat Shaxsiy chat'), ('group', 'Faqat Guruh yoki Kanal'), ('both', 'Ikkalasiga ham'), ('none', 'Yuborilmasin')], default='both', help_text='Kunlik hisobot yuboriladigan manzil', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notify_on_debt',
            field=models.BooleanField(default=True, help_text='Nasiya chegarasi va qarzdorlik haqida ogohlantirish'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notify_on_sale',
            field=models.BooleanField(default=False, help_text="Har bir savdodan so'ng Telegramga xabar yuborish"),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notify_web_reports',
            field=models.BooleanField(default=True, help_text='Smena va kunlik hisobotlarni veb interfeys bildirishnomalariga yuborish'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_footer',
            field=models.TextField(blank=True, default='Xaridingiz uchun rahmat!', help_text='Kassa cheki pastki qismidagi matn/shior'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_header',
            field=models.TextField(blank=True, default='', help_text='Kassa cheki yuqori qismidagi matn'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_phone',
            field=models.CharField(blank=True, default='', help_text="Chekda ko'rinadigan aloqa raqami", max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='shift_report_target',
            field=models.CharField(choices=[('personal', 'Faqat Shaxsiy chat'), ('group', 'Faqat Guruh yoki Kanal'), ('both', 'Ikkalasiga ham'), ('none', 'Yuborilmasin')], default='both', help_text='Smena yopilgandagi Z-hisobot yuboriladigan manzil', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='telegram_group_id',
            field=models.CharField(blank=True, default='', help_text='Telegram guruh yoki kanal ID si (masalan: -1001234567890 yoki @kanal_nomi)', max_length=100),
        ),
    ]
