# Generated by Django 6.1 on 2026-10-06 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_daily_report_target_tenant_notify_on_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='last_low_stock_report_sent_at',
            field=models.DateTimeField(blank=True, help_text="So'nggi marta kamchiliklar hisoboti yuborilgan sana va vaqt", null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='low_stock_day_of_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='Oylik reja uchun oyning sanasi (1 .. 31)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='low_stock_frequency',
            field=models.CharField(choices=[('daily', 'Har kuni'), ('weekly', 'Haftalik'), ('monthly', 'Oylik')], default='daily', help_text='Kamchilik tovarlar hisoboti davriyligi', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='low_stock_report_target',
            field=models.CharField(choices=[('personal', 'Faqat Shaxsiy chat'), ('group', 'Faqat Guruh yoki Kanal'), ('both', 'Ikkalasiga ham'), ('none', 'Yuborilmasin')], default='both', help_text='Kamchilik tovarlar hisoboti yuboriladigan manzil', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='low_stock_report_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Kamayib qolgan tovarlar hisoboti yuboriladigan vaqt (masalan 09:00)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='low_stock_weekday',
            field=models.PositiveSmallIntegerField(default=1, help_text='Haftalik reja uchun hafta kuni (1=Dushanba .. 7=Yakshanba)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notify_web_low_stock',
            field=models.BooleanField(default=True, help_text='Kamayib qolgan tovarlar hisobotini veb interfeys bildirishnomalariga yuborish'),
        ),
    ]
