# Generated by Django 6.1 on 2026-09-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', help_text='Kategoriya valyutasi (UZS yoki USD)', max_length=3),
        ),
    ]
