# Generated by Django 6.1 on 2026-09-29 19:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_tenant_daily_report_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('total_sale_cash_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_sale_cash_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_sale_card_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_sale_card_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_sale_debt_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_sale_debt_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_extra_income_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_extra_income_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_expenses_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_expenses_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('expected_cash_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('expected_cash_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('actual_cash_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('actual_cash_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discrepancy_uzs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discrepancy_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discrepancy_reason', models.TextField(blank=True, default='')),
                ('staff_notes', models.TextField(blank=True, default='')),
                ('is_closed', models.BooleanField(default=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_shifts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='CashIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3)),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_incomes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('shift_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='cashbox.dailycashreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_expenses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('shift_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='cashbox.dailycashreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
