# Generated by Django 6.1 on 2026-10-08 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
        ('tenants', '0007_populate_default_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashexpense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_expenses', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='cashincome',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_incomes', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='dailycashreport',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='tenants.branch'),
        ),
    ]
